apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: jira
  name: jira
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jira
    spec:
      containers:
      - env:
        - name: TZ
          value: '''Asia/Shanghai'''
        image: haxqer/jira
        name: jira-srv
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/jira
          name: home-data
      restartPolicy: Always
      volumes:
      - name: home-data
        persistentVolumeClaim:
          claimName: home-data
status: {}
